function [Best_score, Best_pos, TLBO_curve, res] = runmain(Fun_name, SearchAgents, Max_iterations)
    [lowerbound, upperbound, dimension, fitness] = fun_info(Fun_name); 
    [Best_score, Best_pos, TLBO_curve] = TLBO(SearchAgents, Max_iterations, lowerbound, upperbound, dimension, fitness);
    opt = mpoption('VERBOSE', 0, 'OUT_ALL', 0);
    data = case_ieee30;
    data.gen(:, 6) = Best_pos(1 : 6);
    data.branch(11, 9) = Best_pos(7);
    data.branch(12, 9) = Best_pos(8);
    data.branch(15, 9) = Best_pos(9);
    data.branch(36, 9) = Best_pos(10);
    data.gen(2:6, 2) = Best_pos(21:25);
    data.bus(10, 6) = Best_pos(11);
    data.bus(12, 6) = Best_pos(12);
    data.bus(15, 6) = Best_pos(13);
    data.bus(17, 6) = Best_pos(14);
    data.bus(20, 6) = Best_pos(15);
    data.bus(21, 6) = Best_pos(16);
    data.bus(23, 6) = Best_pos(17);
    data.bus(24, 6) = Best_pos(18);
    data.bus(29, 6) = Best_pos(19);
    res = runpf(data,opt);
end